# Generated by Django 5.1.6 on 2025-04-07 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='teste.competicao')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='teste.time')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='teste.time')),
            ],
        ),
    ]
