# Generated by Django 5.1.6 on 2025-04-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_de_times', models.PositiveIntegerField()),
                ('local', models.CharField(max_length=100)),
            ],
        ),
    ]
