# Generated by Django 5.2 on 2025-04-05 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='teste.competicao')),
                ('jogadores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
