# Generated by Django 5.1.6 on 2025-05-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0011_alter_competicao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='posicao',
            field=models.CharField(blank=True, choices=[('goleiro', 'Goleiro'), ('zagueiro', 'Zagueiro'), ('lateral', 'Lateral'), ('volante', 'Volante'), ('meia', 'Meia'), ('ponta', 'Ponta'), ('atacante', 'Atacante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(max_length=20),
        ),
    ]
