# Generated by Django 5.1.6 on 2025-05-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0012_perfil_altura_perfil_foto_perfil_idade_perfil_peso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicao',
            name='local',
        ),
        migrations.AddField(
            model_name='competicao',
            name='endereco_descritivo',
            field=models.CharField(default='Endereço não informado', max_length=200),
        ),
        migrations.AddField(
            model_name='competicao',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='competicao',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
