# Generated by Django 5.1.6 on 2025-05-15 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0014_convitecompeticao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='cone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios_cone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partida',
            name='joga_de_terno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios_terno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partida',
            name='mvp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partida',
            name='paredao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios_paredao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partida',
            name='xerife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios_xerife', to=settings.AUTH_USER_MODEL),
        ),
    ]
